# Generated by Django 5.2.9 on 2025-12-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_clue"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_rate_limit_declarations", models.BooleanField(default=True)),
                (
                    "rate_limit_declarations",
                    models.CharField(default="5/m", max_length=32),
                ),
                ("enable_captcha_declarations", models.BooleanField(default=True)),
                ("enable_rate_limit_attachments", models.BooleanField(default=True)),
                ("enable_captcha_clues", models.BooleanField(default=False)),
                (
                    "ip_blacklist",
                    models.TextField(blank=True, help_text="One IP per line"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Protection Settings",
            },
        ),
    ]
