# Generated by Django 5.2.9 on 2025-12-04 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_pendingdeclaration_adminsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingdeclaration",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_pending_declarations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="protectionsettings",
            name="activity_log_retention_days",
            field=models.IntegerField(
                default=90, help_text="Auto-delete activity logs after N days"
            ),
        ),
        migrations.AddField(
            model_name="protectionsettings",
            name="admin_session_retention_days",
            field=models.IntegerField(
                default=7, help_text="Auto-delete admin sessions after N days"
            ),
        ),
        migrations.AddField(
            model_name="protectionsettings",
            name="pending_declaration_retention_days",
            field=models.IntegerField(
                default=30,
                help_text="Auto-delete unprocessed pending declarations after N days",
            ),
        ),
    ]
