# Generated by Django 5.2.9 on 2025-12-04 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_pendingdeclaration_processed_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="is_sensitive",
            field=models.BooleanField(
                default=False, help_text="Mark if contains sensitive data"
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="resource_id",
            field=models.CharField(
                blank=True, help_text="ID of the resource affected", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="resource_type",
            field=models.CharField(
                blank=True,
                help_text="Type of resource (Declaration, User, AdminSession, etc.)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("READ", "Read"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("EXPORT", "Export"),
                    ("DOWNLOAD", "Download"),
                    ("UPLOAD", "Upload"),
                    ("VERIFY", "Verify"),
                    ("PROCESS", "Process"),
                    ("REJECT", "Reject"),
                    ("APPROVE", "Approve"),
                    ("BACKUP", "Backup"),
                    ("RESTORE", "Restore"),
                    ("2FA_ENABLE", "2FA Enable"),
                    ("2FA_DISABLE", "2FA Disable"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("PERMISSION_CHANGE", "Permission Change"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="declaration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to="core.declaration",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="details",
            field=models.TextField(blank=True, help_text="JSON details of the change"),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="username",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["-timestamp"], name="core_activi_timesta_8baae3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "-timestamp"], name="core_activi_user_id_d7adda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["action", "-timestamp"], name="core_activi_action_1fc1d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["resource_type", "resource_id"],
                name="core_activi_resourc_bfb71b_idx",
            ),
        ),
    ]
